//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 03:22:18 PM ALMT 
//


package kz.gov.pki.sample.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shinobi" type="{http://pki.gov.kz/sample/soap}shinobi"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shinobi"
})
@XmlRootElement(name = "getShinobiResponse")
public class GetShinobiResponse {

    @XmlElement(required = true)
    protected Shinobi shinobi;

    /**
     * Gets the value of the shinobi property.
     * 
     * @return
     *     possible object is
     *     {@link Shinobi }
     *     
     */
    public Shinobi getShinobi() {
        return shinobi;
    }

    /**
     * Sets the value of the shinobi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shinobi }
     *     
     */
    public void setShinobi(Shinobi value) {
        this.shinobi = value;
    }

}
