//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 03:22:18 PM ALMT 
//


package kz.gov.pki.sample.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.gov.pki.sample.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.gov.pki.sample.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetShinobiRequest }
     * 
     */
    public GetShinobiRequest createGetShinobiRequest() {
        return new GetShinobiRequest();
    }

    /**
     * Create an instance of {@link GetShinobiResponse }
     * 
     */
    public GetShinobiResponse createGetShinobiResponse() {
        return new GetShinobiResponse();
    }

    /**
     * Create an instance of {@link Shinobi }
     * 
     */
    public Shinobi createShinobi() {
        return new Shinobi();
    }

}
