//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 03:22:18 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pki.gov.kz/sample/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kz.gov.pki.sample.soap;
