//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 03:22:18 PM ALMT 
//


package kz.gov.pki.sample.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shinobi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shinobi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="clan" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rogue" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="jutsu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shinobi", propOrder = {
    "name",
    "clan",
    "rogue",
    "jutsu"
})
public class Shinobi {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String clan;
    protected boolean rogue;
    @XmlElement(required = true)
    protected String jutsu;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClan() {
        return clan;
    }

    /**
     * Sets the value of the clan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClan(String value) {
        this.clan = value;
    }

    /**
     * Gets the value of the rogue property.
     * 
     */
    public boolean isRogue() {
        return rogue;
    }

    /**
     * Sets the value of the rogue property.
     * 
     */
    public void setRogue(boolean value) {
        this.rogue = value;
    }

    /**
     * Gets the value of the jutsu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJutsu() {
        return jutsu;
    }

    /**
     * Sets the value of the jutsu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJutsu(String value) {
        this.jutsu = value;
    }

}
